# Generated by Django 5.2.6 on 2026-03-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_order_is_urgent_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Ник в Telegram без @', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('waiting_review', 'На проверке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='open', max_length=20),
        ),
    ]
