# Generated by Django 5.2.6 on 2026-03-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_executor_reviewed_order_student_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='Статус ментора'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверенный'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=200, verbose_name='Навыки (через запятую)'),
        ),
    ]
